# Beanstalk archetype
name = "Beanstalk"
category = "Blue"

game_plans = ["value", "control", "ramp"]
win_conditions = ["creatures", "planeswalkers"]

[subtypes.Bant]
win_conditions = ["creatures", "planeswalkers"]

[subtypes.Domain]
win_conditions = ["creatures", "planeswalkers"]

[subtypes.Sultai]
win_conditions = ["creatures", "planeswalkers"]

[subtypes.Yorion]
win_conditions = ["creatures", "planeswalkers"]
