# Control archetype
name = "Control"
category = "Blue"

game_plans = ["control", "value"]
win_conditions = ["creatures", "planeswalkers", "concede"]

[subtypes.Bant]
win_conditions = ["creatures", "planeswalkers", "concede"]

[subtypes.Esper]
win_conditions = ["creatures", "planeswalkers", "concede"]

[subtypes.Grixis]
win_conditions = ["creatures", "planeswalkers", "concede"]

[subtypes.Jeskai]
win_conditions = ["creatures", "planeswalkers", "concede"]

[subtypes.Sultai]
win_conditions = ["creatures", "planeswalkers", "concede"]
