# Death and Taxes archetype
name = "Death and Taxes"
category = "Non-Blue"

game_plans = ["creatures", "mana denial", "hate"]
win_conditions = ["creatures", "lock-pieces"]

[subtypes.BW]
win_conditions = ["creatures", "lock-pieces"]

[subtypes.W]
win_conditions = ["creatures", "lock-pieces"]

[subtypes.Yorion]
win_conditions = ["creatures", "lock-pieces"]
