# Depths archetype
name = "Depths"
category = "Non-Blue"

game_plans = ["combo", "mana denial"]
win_conditions = ["marit lage", "creatures"]

[subtypes.Golgari]
win_conditions = ["marit lage", "creatures"]

[subtypes.Selesnya]
win_conditions = ["marit lage", "creatures"]

[subtypes.Sultai]
win_conditions = ["marit lage", "creatures"]
