# Depths archetype
name = "Depths"
category = "Non-Blue"

game_plans = ["combo", "mana denial"]
win_conditions = ["marit lage", "creatures"]

[subtypes.GB]
win_conditions = ["marit lage", "creatures"]

[subtypes.GW]
win_conditions = ["marit lage", "creatures"]
