# Doomsday archetype
name = "Doomsday"
category = "Combo"

# Doomsday-specific tracking options (shared across subtypes)
common_pile_types = [
    "Cyclers",
    "Fetch+Cyclers",
    "Brainstorm+LED",
    "Multiple Passes",
    "Chumps",
    "Removal",
    "Jace+LED",
    "Consider+Unearth",
    "Force+Cyclers",
    "Thoughtseize+Cyclers",
    "Cavern+Cyclers",
    "Disruption+Cyclers",
    "Other",
    "Thoughtseize+Cavern",
    "Cavern+Force",
    "Cyclers+Unearth"]

no_doomsday_reasons = [
    "Mana",
    "Counter",
    "Discard",
    "No Doomsday",
    "Life Total",
    "Combo Killed",
    "Gameplan",
]

non_doomsday_wincons = [
    "concede", # e.g. countered oops/storm into the ground
    "creatures",
    "tamiyo-ult",
]

pile_disruption = [
    "Disruptor Flute",
    "Thoughtseize",
    "Force of Will",
    "Endurance",
    "Wasteland",
    "Ghost Quarter",
    "Boseiju, Who Endures",
    "Tishana's Tidebinder",
    "Stifle",
    "Consign to Memory",
    "Force of Negation",
    "Duress",
    "Cabal Therapy",
    "Red Elemental Blast",
    "Pyroblast",
    "Sphere of Resistance",
    "Damping Sphere",
    "Orcish Bowmaster",
    "Lightning Bolt",
    "Deafening Silence",
    "Torpor Orb",
    "Dress Down",
    "Trenchpost",
    "Grindstone",
    "Chalice of the Void",
    "Kozilek's Command",
    "Fatal Push",
    "Swords to Plowshares",
    "Sheoldred's Edict",
    "Null Rod",
    "Echo of Eons",
    "Runehorn Hellkite",
    "Containment Priest",
    "Meddling Mage",
    "Redirect Lightning",
    "Pithing Needle",
    "Trinisphere",
    "Blood Moon",
    "Magus of the Moon",
    "Surgical Extraction",
    "Clarion Conqueror",
    "Snuff Out",
    "Abrupt Decay",
    "Hexing Squelcher",
    "Flusterstorm",
    "Thalia, Guardian of Thraben",
    "Mindbreak Trap",
    "Daze",
    "Goblin Bombardment",
    "Ajani, Nacatl Pariah"]

[subtypes.Turbo]
game_plans = ["combo", "cantrips", "control", "creatures"]
win_conditions = ["doomsday", "other", "creatures"]
loss_reasons = ["bad-pile", "pre-pile-pressure", "mana", "pile-disruption", "combo", "grind"]

[subtypes.Tempo]
game_plans = ["combo", "tamiyo", "cantrips", "control", "creatures"]
win_conditions = ["doomsday", "creatures", "tamiyo-ult", "concede"]
loss_reasons = ["bad-pile", "pre-pile-pressure", "grind", "mana", "pile-disruption", "combo"]

[subtypes.Tempo-Sultai]
game_plans = ["combo", "tamiyo", "cantrips", "control", "creatures"]
win_conditions = ["doomsday", "creatures", "tamiyo-ult", "concede"]
loss_reasons = ["bad-pile", "pre-pile-pressure", "grind", "mana", "pile-disruption", "combo"]
