# Doomsday archetype
name = "Doomsday"
category = "Combo"

# Doomsday-specific tracking options (shared across subtypes)
common_pile_types = [
    "Cyclers",
    "Fetch+Cyclers",
    "Brainstorm+LED",
    "Multiple Passes",
    "Chumps",
    "Removal",
    "Jace+LED",
    "Consider+Unearth",
    "Force+Cyclers",
    "Other",
]

no_doomsday_reasons = [
    "Mana",
    "Counter",
    "Discard",
    "No Doomsday",
    "Life Total",
    "Combo Killed",
    "Gameplan",
]

non_doomsday_wincons = [
    "concede", # e.g. countered oops/storm into the ground
    "creatures",
    "tamiyo-ult",
]

[subtypes.Turbo]
game_plans = ["combo", "cantrips", "control", "creatures"]
win_conditions = ["doomsday", "other", "creatures"]
loss_reasons = ["bad-pile", "pre-pile-pressure", "mana", "pile-disruption", "combo", "grind"]

[subtypes.Turbo.lists]
# Add your Turbo doomsday lists here
# "combo-doomsday-1.0" = "https://moxfield.com/..."
"turbo-doomsday-1.0" = "https://moxfield.com/decks/-8yQN7Uc9ka_u3J8dJcKBg"

[subtypes.Tempo]
game_plans = ["combo", "tamiyo", "cantrips", "control", "creatures"]
win_conditions = ["doomsday", "creatures", "tamiyo-ult", "concede"]
loss_reasons = ["bad-pile", "pre-pile-pressure", "grind", "mana", "pile-disruption", "combo"]

[subtypes.Tempo.lists]
"tempo-doomsday-wasteland-1.0" = "https://moxfield.com/decks/XQ8cIaH-Q0-yjdNzdN3JkQ"
"tempo-doomsday-wasteland-1.1" = "https://moxfield.com/decks/KVLDeRmO2USc5k-Dp5CO1g"
"tempo-doomsday-wasteland-1.2" = "https://moxfield.com/decks/dvIaku_xakGg_Hw0of4IOw"
"tempo-doomsday-wasteland-1.3" = "https://moxfield.com/decks/4LDvJou49k-XpRlKWwXxlg"
"tempo-doomsday-wasteland-1.4" = "https://moxfield.com/decks/r7wdBHrff0W7sb2NYL8UeA"

[subtypes.Tempo-Sultai]
game_plans = ["combo", "tamiyo", "cantrips", "control", "creatures"]
win_conditions = ["doomsday", "creatures", "tamiyo-ult", "concede"]
loss_reasons = ["bad-pile", "pre-pile-pressure", "grind", "mana", "pile-disruption", "combo"]

[subtypes.Tempo-Sultai.lists]
"tempo-doomsday-bug-1.0" = "https://moxfield.com/decks/Hp5JdlOWYUKqlxjwSS6Ndg"
