# Initiative archetype
name = "Initiative"
category = "Non-Blue"

game_plans = ["creatures", "lock-pieces"]
win_conditions = ["creatures"]

[subtypes.Naya]
win_conditions = ["creatures"]

[subtypes.Boros]
win_conditions = ["creatures"]

[subtypes.Gruul]
win_conditions = ["creatures"]
