# Stompy archetype
name = "Stompy"
category = "Non-Blue"

game_plans = ["creatures", "lock-pieces"]
win_conditions = ["creatures", "lock-pieces"]

[subtypes.Eldrazi]
win_conditions = ["creatures"]

[subtypes.Eldrazi.board_plan]
description = "Counter early threats, save removal for Reality Smasher"

[subtypes.Mono-Black]
win_conditions = ["creatures"]

[subtypes.Moon]
win_conditions = ["creatures", "lock-pieces"]

[subtypes.Moon.board_plan]
description = "Counter chalice/moon, remove artifacts, win quickly"
